USE [SOLUM_EXPRESS]
GO
insert into "@EX_PROCESO" (Code,Name,Type,State) values ('SAP_UPDATE_DESPACHO','ENVIO PARA ACTUALIZAR DATOS DE TRACKING DE DESPACHO MULTICLIENTE',0,0)
insert into "@EX_PROCESO" (Code,Name,Type,State) values ('SAP_UPDATE_LIQUIDACION','ENVIO PARA ACTUALIZAR DATOS DE TRACKING DE LIQUIDACION MULTICLIENTE',0,0)
--delete from "@EX_PROCESO" where Code = 'SAP_UPDATE_DESPACHO'
--delete from "@EX_PROCESO" where Code = 'SAP_UPDATE_LIQUIDACION'
insert into "@EX_RUTA" (Code,U_EX_CLIENTE,U_EX_PROCESO,U_EX_MODELO,Environment,Server,Port,Route,Sftp,Historic,UserSap,Password,Email,Subject,Attached,Zip,State,LogErr)
values (181,'20100310288','SAP_UPDATE_LIQUIDACION',NULL,0,NULL,NULL,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\',0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\HIS\',NULL,NULL,1,'Envio de Interfaz de liquidacion a SAP',0,0,0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\LOG\')
insert into "@EX_RUTA" (Code,U_EX_CLIENTE,U_EX_PROCESO,U_EX_MODELO,Environment,Server,Port,Route,Sftp,Historic,UserSap,Password,Email,Subject,Attached,Zip,State,LogErr)
values (182,'20167884491','SAP_UPDATE_LIQUIDACION',NULL,0,NULL,NULL,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\',0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\HIS\',NULL,NULL,1,'Envio de Interfaz de liquidacion a SAP',0,0,0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\LOG\')
insert into "@EX_RUTA" (Code,U_EX_CLIENTE,U_EX_PROCESO,U_EX_MODELO,Environment,Server,Port,Route,Sftp,Historic,UserSap,Password,Email,Subject,Attached,Zip,State,LogErr)
values (183,'20605977406','SAP_UPDATE_LIQUIDACION',NULL,0,NULL,NULL,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\',0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\HIS\',NULL,NULL,1,'Envio de Interfaz de liquidacion a SAP',0,0,0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\LOG\')
insert into "@EX_RUTA" (Code,U_EX_CLIENTE,U_EX_PROCESO,U_EX_MODELO,Environment,Server,Port,Route,Sftp,Historic,UserSap,Password,Email,Subject,Attached,Zip,State,LogErr)
values (184,'20609268779','SAP_UPDATE_LIQUIDACION',NULL,0,NULL,NULL,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\',0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\HIS\',NULL,NULL,1,'Envio de Interfaz de liquidacion a SAP',0,0,0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\LOG\')
insert into "@EX_RUTA" (Code,U_EX_CLIENTE,U_EX_PROCESO,U_EX_MODELO,Environment,Server,Port,Route,Sftp,Historic,UserSap,Password,Email,Subject,Attached,Zip,State,LogErr)
values (185,'20608718657','SAP_UPDATE_LIQUIDACION',NULL,0,NULL,NULL,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\',0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\HIS\',NULL,NULL,1,'Envio de Interfaz de liquidacion a SAP',0,0,0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\LOG\')
insert into "@EX_RUTA" (Code,U_EX_CLIENTE,U_EX_PROCESO,U_EX_MODELO,Environment,Server,Port,Route,Sftp,Historic,UserSap,Password,Email,Subject,Attached,Zip,State,LogErr)
values (186,'20608323725','SAP_UPDATE_LIQUIDACION',NULL,0,NULL,NULL,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\',0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\HIS\',NULL,NULL,1,'Envio de Interfaz de liquidacion a SAP',0,0,0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\LOG\')
insert into "@EX_RUTA" (Code,U_EX_CLIENTE,U_EX_PROCESO,U_EX_MODELO,Environment,Server,Port,Route,Sftp,Historic,UserSap,Password,Email,Subject,Attached,Zip,State,LogErr)
values (187,'20605419004','SAP_UPDATE_LIQUIDACION',NULL,0,NULL,NULL,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\',0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\HIS\',NULL,NULL,1,'Envio de Interfaz de liquidacion a SAP',0,0,0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\LOG\')
insert into "@EX_RUTA" (Code,U_EX_CLIENTE,U_EX_PROCESO,U_EX_MODELO,Environment,Server,Port,Route,Sftp,Historic,UserSap,Password,Email,Subject,Attached,Zip,State,LogErr)
values (188,'20604009741','SAP_UPDATE_LIQUIDACION',NULL,0,NULL,NULL,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\',0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\HIS\',NULL,NULL,1,'Envio de Interfaz de liquidacion a SAP',0,0,0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\LOG\')
insert into "@EX_RUTA" (Code,U_EX_CLIENTE,U_EX_PROCESO,U_EX_MODELO,Environment,Server,Port,Route,Sftp,Historic,UserSap,Password,Email,Subject,Attached,Zip,State,LogErr)
values (189,'20566160987','SAP_UPDATE_LIQUIDACION',NULL,0,NULL,NULL,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\',0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\HIS\',NULL,NULL,1,'Envio de Interfaz de liquidacion a SAP',0,0,0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\LOG\')
insert into "@EX_RUTA" (Code,U_EX_CLIENTE,U_EX_PROCESO,U_EX_MODELO,Environment,Server,Port,Route,Sftp,Historic,UserSap,Password,Email,Subject,Attached,Zip,State,LogErr)
values (190,'20557203550','SAP_UPDATE_LIQUIDACION',NULL,0,NULL,NULL,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\',0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\HIS\',NULL,NULL,1,'Envio de Interfaz de liquidacion a SAP',0,0,0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\LOG\')
insert into "@EX_RUTA" (Code,U_EX_CLIENTE,U_EX_PROCESO,U_EX_MODELO,Environment,Server,Port,Route,Sftp,Historic,UserSap,Password,Email,Subject,Attached,Zip,State,LogErr)
values (191,'20555712791','SAP_UPDATE_LIQUIDACION',NULL,0,NULL,NULL,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\',0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\HIS\',NULL,NULL,1,'Envio de Interfaz de liquidacion a SAP',0,0,0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\LOG\')
insert into "@EX_RUTA" (Code,U_EX_CLIENTE,U_EX_PROCESO,U_EX_MODELO,Environment,Server,Port,Route,Sftp,Historic,UserSap,Password,Email,Subject,Attached,Zip,State,LogErr)
values (192,'20551288120','SAP_UPDATE_LIQUIDACION',NULL,0,NULL,NULL,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\',0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\HIS\',NULL,NULL,1,'Envio de Interfaz de liquidacion a SAP',0,0,0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\LOG\')
insert into "@EX_RUTA" (Code,U_EX_CLIENTE,U_EX_PROCESO,U_EX_MODELO,Environment,Server,Port,Route,Sftp,Historic,UserSap,Password,Email,Subject,Attached,Zip,State,LogErr)
values (193,'20547904223','SAP_UPDATE_LIQUIDACION',NULL,0,NULL,NULL,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\',0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\HIS\',NULL,NULL,1,'Envio de Interfaz de liquidacion a SAP',0,0,0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\LOG\')
insert into "@EX_RUTA" (Code,U_EX_CLIENTE,U_EX_PROCESO,U_EX_MODELO,Environment,Server,Port,Route,Sftp,Historic,UserSap,Password,Email,Subject,Attached,Zip,State,LogErr)
values (194,'20537821249','SAP_UPDATE_LIQUIDACION',NULL,0,NULL,NULL,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\',0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\HIS\',NULL,NULL,1,'Envio de Interfaz de liquidacion a SAP',0,0,0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\LOG\')
insert into "@EX_RUTA" (Code,U_EX_CLIENTE,U_EX_PROCESO,U_EX_MODELO,Environment,Server,Port,Route,Sftp,Historic,UserSap,Password,Email,Subject,Attached,Zip,State,LogErr)
values (195,'20519478511','SAP_UPDATE_LIQUIDACION',NULL,0,NULL,NULL,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\',0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\HIS\',NULL,NULL,1,'Envio de Interfaz de liquidacion a SAP',0,0,0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\LOG\')
insert into "@EX_RUTA" (Code,U_EX_CLIENTE,U_EX_PROCESO,U_EX_MODELO,Environment,Server,Port,Route,Sftp,Historic,UserSap,Password,Email,Subject,Attached,Zip,State,LogErr)
values (196,'20513309351','SAP_UPDATE_LIQUIDACION',NULL,0,NULL,NULL,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\',0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\HIS\',NULL,NULL,1,'Envio de Interfaz de liquidacion a SAP',0,0,0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\LOG\')
insert into "@EX_RUTA" (Code,U_EX_CLIENTE,U_EX_PROCESO,U_EX_MODELO,Environment,Server,Port,Route,Sftp,Historic,UserSap,Password,Email,Subject,Attached,Zip,State,LogErr)
values (197,'20509675491','SAP_UPDATE_LIQUIDACION',NULL,0,NULL,NULL,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\',0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\HIS\',NULL,NULL,1,'Envio de Interfaz de liquidacion a SAP',0,0,0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\LOG\')
insert into "@EX_RUTA" (Code,U_EX_CLIENTE,U_EX_PROCESO,U_EX_MODELO,Environment,Server,Port,Route,Sftp,Historic,UserSap,Password,Email,Subject,Attached,Zip,State,LogErr)
values (198,'20504498744','SAP_UPDATE_LIQUIDACION',NULL,0,NULL,NULL,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\',0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\HIS\',NULL,NULL,1,'Envio de Interfaz de liquidacion a SAP',0,0,0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\LOG\')
insert into "@EX_RUTA" (Code,U_EX_CLIENTE,U_EX_PROCESO,U_EX_MODELO,Environment,Server,Port,Route,Sftp,Historic,UserSap,Password,Email,Subject,Attached,Zip,State,LogErr)
values (199,'20458805165','SAP_UPDATE_LIQUIDACION',NULL,0,NULL,NULL,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\',0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\HIS\',NULL,NULL,1,'Envio de Interfaz de liquidacion a SAP',0,0,0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\LOG\')
insert into "@EX_RUTA" (Code,U_EX_CLIENTE,U_EX_PROCESO,U_EX_MODELO,Environment,Server,Port,Route,Sftp,Historic,UserSap,Password,Email,Subject,Attached,Zip,State,LogErr)
values (200,'20381600441','SAP_UPDATE_LIQUIDACION',NULL,0,NULL,NULL,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\',0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\HIS\',NULL,NULL,1,'Envio de Interfaz de liquidacion a SAP',0,0,0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\LOG\')
insert into "@EX_RUTA" (Code,U_EX_CLIENTE,U_EX_PROCESO,U_EX_MODELO,Environment,Server,Port,Route,Sftp,Historic,UserSap,Password,Email,Subject,Attached,Zip,State,LogErr)
values (201,'20378890161','SAP_UPDATE_LIQUIDACION',NULL,0,NULL,NULL,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\',0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\HIS\',NULL,NULL,1,'Envio de Interfaz de liquidacion a SAP',0,0,0,'C:\FTP Clientes\GENERAL\IN\LIQUIDACION\LOG\')

--delete from "@EX_RUTA" where U_EX_PROCESO = 'SAP_UPDATE_LIQUIDACION'
--select * from "@EX_RUTA" where Code = 162
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(236,181,'TRACKING_LIQUIDACION_20100310288_','TXT','\t',NULL,0,'SAP_HOST_LIQUIDACION',NULL,NULL)
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(237,181,'SAP_HOST_LIQUIDACION',NULL,NULL,NULL,0,'SAP_HOST_LIQUIDACION',4,'exec BZ_JEPM_ACTUALIZAR_LIQUIDACION_ODLN @@SOCIEDAD , @@HGUI ')
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(238,182,'TRACKING_LIQUIDACION_20167884491_','TXT','\t',NULL,0,'SAP_HOST_LIQUIDACION',NULL,NULL)
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(239,182,'SAP_HOST_LIQUIDACION',NULL,NULL,NULL,0,'SAP_HOST_LIQUIDACION',4,'exec BZ_JEPM_ACTUALIZAR_LIQUIDACION_ODLN @@SOCIEDAD , @@HGUI ')
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(240,183,'TRACKING_LIQUIDACION_20605977406_','TXT','\t',NULL,0,'SAP_HOST_LIQUIDACION',NULL,NULL)
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(241,183,'SAP_HOST_LIQUIDACION',NULL,NULL,NULL,0,'SAP_HOST_LIQUIDACION',4,'exec BZ_JEPM_ACTUALIZAR_LIQUIDACION_ODLN @@SOCIEDAD , @@HGUI ')
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(242,184,'TRACKING_LIQUIDACION_20609268779_','TXT','\t',NULL,0,'SAP_HOST_LIQUIDACION',NULL,NULL)
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(243,184,'SAP_HOST_LIQUIDACION',NULL,NULL,NULL,0,'SAP_HOST_LIQUIDACION',4,'exec BZ_JEPM_ACTUALIZAR_LIQUIDACION_ODLN @@SOCIEDAD , @@HGUI ')
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(244,185,'TRACKING_LIQUIDACION_20608718657_','TXT','\t',NULL,0,'SAP_HOST_LIQUIDACION',NULL,NULL)
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(245,185,'SAP_HOST_LIQUIDACION',NULL,NULL,NULL,0,'SAP_HOST_LIQUIDACION',4,'exec BZ_JEPM_ACTUALIZAR_LIQUIDACION_ODLN @@SOCIEDAD , @@HGUI ')
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(246,186,'TRACKING_LIQUIDACION_20608323725_','TXT','\t',NULL,0,'SAP_HOST_LIQUIDACION',NULL,NULL)
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(247,186,'SAP_HOST_LIQUIDACION',NULL,NULL,NULL,0,'SAP_HOST_LIQUIDACION',4,'exec BZ_JEPM_ACTUALIZAR_LIQUIDACION_ODLN @@SOCIEDAD , @@HGUI ')
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(248,187,'TRACKING_LIQUIDACION_20605419004_','TXT','\t',NULL,0,'SAP_HOST_LIQUIDACION',NULL,NULL)
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(249,187,'SAP_HOST_LIQUIDACION',NULL,NULL,NULL,0,'SAP_HOST_LIQUIDACION',4,'exec BZ_JEPM_ACTUALIZAR_LIQUIDACION_ODLN @@SOCIEDAD , @@HGUI ')
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(250,188,'TRACKING_LIQUIDACION_20604009741_','TXT','\t',NULL,0,'SAP_HOST_LIQUIDACION',NULL,NULL)
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(251,188,'SAP_HOST_LIQUIDACION',NULL,NULL,NULL,0,'SAP_HOST_LIQUIDACION',4,'exec BZ_JEPM_ACTUALIZAR_LIQUIDACION_ODLN @@SOCIEDAD , @@HGUI ')
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(252,189,'TRACKING_LIQUIDACION_20566160987_','TXT','\t',NULL,0,'SAP_HOST_LIQUIDACION',NULL,NULL)
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(253,189,'SAP_HOST_LIQUIDACION',NULL,NULL,NULL,0,'SAP_HOST_LIQUIDACION',4,'exec BZ_JEPM_ACTUALIZAR_LIQUIDACION_ODLN @@SOCIEDAD , @@HGUI ')
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(254,190,'TRACKING_LIQUIDACION_20557203550_','TXT','\t',NULL,0,'SAP_HOST_LIQUIDACION',NULL,NULL)
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(255,190,'SAP_HOST_LIQUIDACION',NULL,NULL,NULL,0,'SAP_HOST_LIQUIDACION',4,'exec BZ_JEPM_ACTUALIZAR_LIQUIDACION_ODLN @@SOCIEDAD , @@HGUI ')
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(256,191,'TRACKING_LIQUIDACION_20555712791_','TXT','\t',NULL,0,'SAP_HOST_LIQUIDACION',NULL,NULL)
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(257,191,'SAP_HOST_LIQUIDACION',NULL,NULL,NULL,0,'SAP_HOST_LIQUIDACION',4,'exec BZ_JEPM_ACTUALIZAR_LIQUIDACION_ODLN @@SOCIEDAD , @@HGUI ')
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(258,192,'TRACKING_LIQUIDACION_20551288120_','TXT','\t',NULL,0,'SAP_HOST_LIQUIDACION',NULL,NULL)
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(259,192,'SAP_HOST_LIQUIDACION',NULL,NULL,NULL,0,'SAP_HOST_LIQUIDACION',4,'exec BZ_JEPM_ACTUALIZAR_LIQUIDACION_ODLN @@SOCIEDAD , @@HGUI ')
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(260,193,'TRACKING_LIQUIDACION_20547904223_','TXT','\t',NULL,0,'SAP_HOST_LIQUIDACION',NULL,NULL)
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(261,193,'SAP_HOST_LIQUIDACION',NULL,NULL,NULL,0,'SAP_HOST_LIQUIDACION',4,'exec BZ_JEPM_ACTUALIZAR_LIQUIDACION_ODLN @@SOCIEDAD , @@HGUI ')
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(262,194,'TRACKING_LIQUIDACION_20537821249_','TXT','\t',NULL,0,'SAP_HOST_LIQUIDACION',NULL,NULL)
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(263,194,'SAP_HOST_LIQUIDACION',NULL,NULL,NULL,0,'SAP_HOST_LIQUIDACION',4,'exec BZ_JEPM_ACTUALIZAR_LIQUIDACION_ODLN @@SOCIEDAD , @@HGUI ')
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(264,195,'TRACKING_LIQUIDACION_20519478511_','TXT','\t',NULL,0,'SAP_HOST_LIQUIDACION',NULL,NULL)
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(265,195,'SAP_HOST_LIQUIDACION',NULL,NULL,NULL,0,'SAP_HOST_LIQUIDACION',4,'exec BZ_JEPM_ACTUALIZAR_LIQUIDACION_ODLN @@SOCIEDAD , @@HGUI ')
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(266,196,'TRACKING_LIQUIDACION_20513309351_','TXT','\t',NULL,0,'SAP_HOST_LIQUIDACION',NULL,NULL)
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(267,196,'SAP_HOST_LIQUIDACION',NULL,NULL,NULL,0,'SAP_HOST_LIQUIDACION',4,'exec BZ_JEPM_ACTUALIZAR_LIQUIDACION_ODLN @@SOCIEDAD , @@HGUI ')
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(268,197,'TRACKING_LIQUIDACION_20509675491_','TXT','\t',NULL,0,'SAP_HOST_LIQUIDACION',NULL,NULL)
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(269,197,'SAP_HOST_LIQUIDACION',NULL,NULL,NULL,0,'SAP_HOST_LIQUIDACION',4,'exec BZ_JEPM_ACTUALIZAR_LIQUIDACION_ODLN @@SOCIEDAD , @@HGUI ')
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(270,198,'TRACKING_LIQUIDACION_20504498744_','TXT','\t',NULL,0,'SAP_HOST_LIQUIDACION',NULL,NULL)
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(271,198,'SAP_HOST_LIQUIDACION',NULL,NULL,NULL,0,'SAP_HOST_LIQUIDACION',4,'exec BZ_JEPM_ACTUALIZAR_LIQUIDACION_ODLN @@SOCIEDAD , @@HGUI ')
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(272,199,'TRACKING_LIQUIDACION_20458805165_','TXT','\t',NULL,0,'SAP_HOST_LIQUIDACION',NULL,NULL)
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(273,199,'SAP_HOST_LIQUIDACION',NULL,NULL,NULL,0,'SAP_HOST_LIQUIDACION',4,'exec BZ_JEPM_ACTUALIZAR_LIQUIDACION_ODLN @@SOCIEDAD , @@HGUI ')
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(274,200,'TRACKING_LIQUIDACION_20381600441_','TXT','\t',NULL,0,'SAP_HOST_LIQUIDACION',NULL,NULL)
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(275,200,'SAP_HOST_LIQUIDACION',NULL,NULL,NULL,0,'SAP_HOST_LIQUIDACION',4,'exec BZ_JEPM_ACTUALIZAR_LIQUIDACION_ODLN @@SOCIEDAD , @@HGUI ')
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(276,201,'TRACKING_LIQUIDACION_20378890161_','TXT','\t',NULL,0,'SAP_HOST_LIQUIDACION',NULL,NULL)
insert into "@EX_FILE" (Code,U_EX_RUTA,Prefix,Extent,Separator,[Order],State,Destino,Type,SAttribute) values(277,201,'SAP_HOST_LIQUIDACION',NULL,NULL,NULL,0,'SAP_HOST_LIQUIDACION',4,'exec BZ_JEPM_ACTUALIZAR_LIQUIDACION_ODLN @@SOCIEDAD , @@HGUI ')
--delete from "@EX_FILE" where U_EX_RUTA >=181 AND EX_RUTA <= 201
--select * from "@EX_FILE" where U_EX_RUTA = 160
--select * from "@EX_FILE" where U_EX_RUTA = 161
--alter table "@EX_FILE" add Type int null
--alter table "@EX_FILE" add SAttribute varchar(max) null
insert into [@EX_PLANIFICADO] (U_EX_CLIENTE,U_EX_PROCESO,tipo,hora,minuto,lunes,martes,miercoles,jueves,viernes,sabado,domingo,modalidad,titulo,datos,fechainicio,fechafin,State) 
values('20100310288','SAP_UPDATE_LIQUIDACION',0,NULL,NULL,1,1,1,1,1,1,1,2,1,3,NULL,NULL,0)
insert into [@EX_PLANIFICADO] (U_EX_CLIENTE,U_EX_PROCESO,tipo,hora,minuto,lunes,martes,miercoles,jueves,viernes,sabado,domingo,modalidad,titulo,datos,fechainicio,fechafin,State) 
values('20167884491','SAP_UPDATE_LIQUIDACION',0,NULL,NULL,1,1,1,1,1,1,1,2,1,3,NULL,NULL,0)
insert into [@EX_PLANIFICADO] (U_EX_CLIENTE,U_EX_PROCESO,tipo,hora,minuto,lunes,martes,miercoles,jueves,viernes,sabado,domingo,modalidad,titulo,datos,fechainicio,fechafin,State) 
values('20605977406','SAP_UPDATE_LIQUIDACION',0,NULL,NULL,1,1,1,1,1,1,1,2,1,3,NULL,NULL,0)
insert into [@EX_PLANIFICADO] (U_EX_CLIENTE,U_EX_PROCESO,tipo,hora,minuto,lunes,martes,miercoles,jueves,viernes,sabado,domingo,modalidad,titulo,datos,fechainicio,fechafin,State) 
values('20609268779','SAP_UPDATE_LIQUIDACION',0,NULL,NULL,1,1,1,1,1,1,1,2,1,3,NULL,NULL,0)
insert into [@EX_PLANIFICADO] (U_EX_CLIENTE,U_EX_PROCESO,tipo,hora,minuto,lunes,martes,miercoles,jueves,viernes,sabado,domingo,modalidad,titulo,datos,fechainicio,fechafin,State) 
values('20608718657','SAP_UPDATE_LIQUIDACION',0,NULL,NULL,1,1,1,1,1,1,1,2,1,3,NULL,NULL,0)
insert into [@EX_PLANIFICADO] (U_EX_CLIENTE,U_EX_PROCESO,tipo,hora,minuto,lunes,martes,miercoles,jueves,viernes,sabado,domingo,modalidad,titulo,datos,fechainicio,fechafin,State) 
values('20608323725','SAP_UPDATE_LIQUIDACION',0,NULL,NULL,1,1,1,1,1,1,1,2,1,3,NULL,NULL,0)
insert into [@EX_PLANIFICADO] (U_EX_CLIENTE,U_EX_PROCESO,tipo,hora,minuto,lunes,martes,miercoles,jueves,viernes,sabado,domingo,modalidad,titulo,datos,fechainicio,fechafin,State) 
values('20605419004','SAP_UPDATE_LIQUIDACION',0,NULL,NULL,1,1,1,1,1,1,1,2,1,3,NULL,NULL,0)
insert into [@EX_PLANIFICADO] (U_EX_CLIENTE,U_EX_PROCESO,tipo,hora,minuto,lunes,martes,miercoles,jueves,viernes,sabado,domingo,modalidad,titulo,datos,fechainicio,fechafin,State) 
values('20604009741','SAP_UPDATE_LIQUIDACION',0,NULL,NULL,1,1,1,1,1,1,1,2,1,3,NULL,NULL,0)
insert into [@EX_PLANIFICADO] (U_EX_CLIENTE,U_EX_PROCESO,tipo,hora,minuto,lunes,martes,miercoles,jueves,viernes,sabado,domingo,modalidad,titulo,datos,fechainicio,fechafin,State) 
values('20566160987','SAP_UPDATE_LIQUIDACION',0,NULL,NULL,1,1,1,1,1,1,1,2,1,3,NULL,NULL,0)
insert into [@EX_PLANIFICADO] (U_EX_CLIENTE,U_EX_PROCESO,tipo,hora,minuto,lunes,martes,miercoles,jueves,viernes,sabado,domingo,modalidad,titulo,datos,fechainicio,fechafin,State) 
values('20557203550','SAP_UPDATE_LIQUIDACION',0,NULL,NULL,1,1,1,1,1,1,1,2,1,3,NULL,NULL,0)
insert into [@EX_PLANIFICADO] (U_EX_CLIENTE,U_EX_PROCESO,tipo,hora,minuto,lunes,martes,miercoles,jueves,viernes,sabado,domingo,modalidad,titulo,datos,fechainicio,fechafin,State) 
values('20555712791','SAP_UPDATE_LIQUIDACION',0,NULL,NULL,1,1,1,1,1,1,1,2,1,3,NULL,NULL,0)
insert into [@EX_PLANIFICADO] (U_EX_CLIENTE,U_EX_PROCESO,tipo,hora,minuto,lunes,martes,miercoles,jueves,viernes,sabado,domingo,modalidad,titulo,datos,fechainicio,fechafin,State) 
values('20551288120','SAP_UPDATE_LIQUIDACION',0,NULL,NULL,1,1,1,1,1,1,1,2,1,3,NULL,NULL,0)
insert into [@EX_PLANIFICADO] (U_EX_CLIENTE,U_EX_PROCESO,tipo,hora,minuto,lunes,martes,miercoles,jueves,viernes,sabado,domingo,modalidad,titulo,datos,fechainicio,fechafin,State) 
values('20547904223','SAP_UPDATE_LIQUIDACION',0,NULL,NULL,1,1,1,1,1,1,1,2,1,3,NULL,NULL,0)
insert into [@EX_PLANIFICADO] (U_EX_CLIENTE,U_EX_PROCESO,tipo,hora,minuto,lunes,martes,miercoles,jueves,viernes,sabado,domingo,modalidad,titulo,datos,fechainicio,fechafin,State) 
values('20537821249','SAP_UPDATE_LIQUIDACION',0,NULL,NULL,1,1,1,1,1,1,1,2,1,3,NULL,NULL,0)
insert into [@EX_PLANIFICADO] (U_EX_CLIENTE,U_EX_PROCESO,tipo,hora,minuto,lunes,martes,miercoles,jueves,viernes,sabado,domingo,modalidad,titulo,datos,fechainicio,fechafin,State) 
values('20519478511','SAP_UPDATE_LIQUIDACION',0,NULL,NULL,1,1,1,1,1,1,1,2,1,3,NULL,NULL,0)
insert into [@EX_PLANIFICADO] (U_EX_CLIENTE,U_EX_PROCESO,tipo,hora,minuto,lunes,martes,miercoles,jueves,viernes,sabado,domingo,modalidad,titulo,datos,fechainicio,fechafin,State) 
values('20513309351','SAP_UPDATE_LIQUIDACION',0,NULL,NULL,1,1,1,1,1,1,1,2,1,3,NULL,NULL,0)
insert into [@EX_PLANIFICADO] (U_EX_CLIENTE,U_EX_PROCESO,tipo,hora,minuto,lunes,martes,miercoles,jueves,viernes,sabado,domingo,modalidad,titulo,datos,fechainicio,fechafin,State) 
values('20509675491','SAP_UPDATE_LIQUIDACION',0,NULL,NULL,1,1,1,1,1,1,1,2,1,3,NULL,NULL,0)
insert into [@EX_PLANIFICADO] (U_EX_CLIENTE,U_EX_PROCESO,tipo,hora,minuto,lunes,martes,miercoles,jueves,viernes,sabado,domingo,modalidad,titulo,datos,fechainicio,fechafin,State) 
values('20504498744','SAP_UPDATE_LIQUIDACION',0,NULL,NULL,1,1,1,1,1,1,1,2,1,3,NULL,NULL,0)
insert into [@EX_PLANIFICADO] (U_EX_CLIENTE,U_EX_PROCESO,tipo,hora,minuto,lunes,martes,miercoles,jueves,viernes,sabado,domingo,modalidad,titulo,datos,fechainicio,fechafin,State) 
values('20458805165','SAP_UPDATE_LIQUIDACION',0,NULL,NULL,1,1,1,1,1,1,1,2,1,3,NULL,NULL,0)
insert into [@EX_PLANIFICADO] (U_EX_CLIENTE,U_EX_PROCESO,tipo,hora,minuto,lunes,martes,miercoles,jueves,viernes,sabado,domingo,modalidad,titulo,datos,fechainicio,fechafin,State) 
values('20381600441','SAP_UPDATE_LIQUIDACION',0,NULL,NULL,1,1,1,1,1,1,1,2,1,3,NULL,NULL,0)
insert into [@EX_PLANIFICADO] (U_EX_CLIENTE,U_EX_PROCESO,tipo,hora,minuto,lunes,martes,miercoles,jueves,viernes,sabado,domingo,modalidad,titulo,datos,fechainicio,fechafin,State) 
values('20378890161','SAP_UPDATE_LIQUIDACION',0,NULL,NULL,1,1,1,1,1,1,1,2,1,3,NULL,NULL,0)
--delete from [@EX_PLANIFICADO] where U_EX_PROCESO = 'SAP_UPDATE_LIQUIDACION'
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(451,181,'operador.3pl@solum-logistics.com','$olum$2021',0,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(452,181,'epariona.sistemas@gmail.com','',2,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(453,181,'angel.uribe@boostersolutions.com ','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(454,182,'operador.3pl@solum-logistics.com','$olum$2021',0,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(455,182,'epariona.sistemas@gmail.com','',2,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(456,182,'angel.uribe@boostersolutions.com ','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(457,183,'operador.3pl@solum-logistics.com','$olum$2021',0,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(458,183,'epariona.sistemas@gmail.com','',2,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(459,183,'angel.uribe@boostersolutions.com ','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(460,184,'operador.3pl@solum-logistics.com','$olum$2021',0,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(461,184,'epariona.sistemas@gmail.com','',2,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(462,184,'angel.uribe@boostersolutions.com ','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(463,185,'operador.3pl@solum-logistics.com','$olum$2021',0,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(464,185,'epariona.sistemas@gmail.com','',2,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(465,185,'angel.uribe@boostersolutions.com ','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(466,186,'operador.3pl@solum-logistics.com','$olum$2021',0,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(467,186,'epariona.sistemas@gmail.com','',2,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(468,186,'angel.uribe@boostersolutions.com ','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(469,187,'operador.3pl@solum-logistics.com','$olum$2021',0,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(470,187,'epariona.sistemas@gmail.com','',2,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(471,187,'angel.uribe@boostersolutions.com ','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(472,188,'operador.3pl@solum-logistics.com','$olum$2021',0,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(473,188,'epariona.sistemas@gmail.com','',2,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(474,188,'angel.uribe@boostersolutions.com ','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(475,189,'operador.3pl@solum-logistics.com','$olum$2021',0,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(476,189,'epariona.sistemas@gmail.com','',2,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(477,189,'angel.uribe@boostersolutions.com ','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(478,190,'operador.3pl@solum-logistics.com','$olum$2021',0,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(479,190,'epariona.sistemas@gmail.com','',2,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(480,190,'angel.uribe@boostersolutions.com ','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(481,191,'operador.3pl@solum-logistics.com','$olum$2021',0,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(482,191,'epariona.sistemas@gmail.com','',2,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(483,191,'angel.uribe@boostersolutions.com ','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(484,192,'operador.3pl@solum-logistics.com','$olum$2021',0,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(485,192,'epariona.sistemas@gmail.com','',2,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(486,192,'angel.uribe@boostersolutions.com ','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(487,193,'operador.3pl@solum-logistics.com','$olum$2021',0,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(488,193,'epariona.sistemas@gmail.com','',2,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(489,193,'angel.uribe@boostersolutions.com ','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(490,194,'operador.3pl@solum-logistics.com','$olum$2021',0,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(491,194,'epariona.sistemas@gmail.com','',2,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(492,194,'angel.uribe@boostersolutions.com ','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(493,195,'operador.3pl@solum-logistics.com','$olum$2021',0,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(494,195,'epariona.sistemas@gmail.com','',2,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(495,195,'angel.uribe@boostersolutions.com ','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(496,196,'operador.3pl@solum-logistics.com','$olum$2021',0,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(497,196,'epariona.sistemas@gmail.com','',2,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(498,196,'angel.uribe@boostersolutions.com ','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(499,197,'operador.3pl@solum-logistics.com','$olum$2021',0,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(500,197,'epariona.sistemas@gmail.com','',2,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(501,197,'angel.uribe@boostersolutions.com ','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(502,198,'operador.3pl@solum-logistics.com','$olum$2021',0,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(503,198,'epariona.sistemas@gmail.com','',2,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(504,198,'angel.uribe@boostersolutions.com ','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(505,199,'operador.3pl@solum-logistics.com','$olum$2021',0,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(506,199,'epariona.sistemas@gmail.com','',2,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(507,199,'angel.uribe@boostersolutions.com ','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(508,200,'operador.3pl@solum-logistics.com','$olum$2021',0,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(509,200,'epariona.sistemas@gmail.com','',2,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(510,200,'angel.uribe@boostersolutions.com ','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(511,201,'operador.3pl@solum-logistics.com','$olum$2021',0,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(512,201,'epariona.sistemas@gmail.com','',2,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(513,201,'angel.uribe@boostersolutions.com ','',1,0)

insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(598,181,'miguel.garcia@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(599,181,'frank.prado@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(600,181,'programacion.despacho@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(601,181,'ecommerce.lurin@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(602,182,'miguel.garcia@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(603,182,'frank.prado@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(604,182,'programacion.despacho@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(605,182,'ecommerce.lurin@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(606,183,'miguel.garcia@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(607,183,'frank.prado@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(608,183,'programacion.despacho@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(609,183,'ecommerce.lurin@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(610,184,'miguel.garcia@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(611,184,'frank.prado@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(612,184,'programacion.despacho@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(613,184,'ecommerce.lurin@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(614,185,'miguel.garcia@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(615,185,'frank.prado@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(616,185,'programacion.despacho@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(617,185,'ecommerce.lurin@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(618,186,'miguel.garcia@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(619,186,'frank.prado@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(620,186,'programacion.despacho@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(621,186,'ecommerce.lurin@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(622,187,'miguel.garcia@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(623,187,'frank.prado@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(624,187,'programacion.despacho@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(625,187,'ecommerce.lurin@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(626,188,'miguel.garcia@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(627,188,'frank.prado@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(628,188,'programacion.despacho@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(629,188,'ecommerce.lurin@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(630,189,'miguel.garcia@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(631,189,'frank.prado@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(632,189,'programacion.despacho@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(633,189,'ecommerce.lurin@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(634,190,'miguel.garcia@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(635,190,'frank.prado@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(636,190,'programacion.despacho@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(637,190,'ecommerce.lurin@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(638,191,'miguel.garcia@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(639,191,'frank.prado@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(640,191,'programacion.despacho@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(641,191,'ecommerce.lurin@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(642,192,'miguel.garcia@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(643,192,'frank.prado@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(644,192,'programacion.despacho@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(645,192,'ecommerce.lurin@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(646,193,'miguel.garcia@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(647,193,'frank.prado@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(648,193,'programacion.despacho@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(649,193,'ecommerce.lurin@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(650,194,'miguel.garcia@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(651,194,'frank.prado@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(652,194,'programacion.despacho@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(653,194,'ecommerce.lurin@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(654,195,'miguel.garcia@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(655,195,'frank.prado@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(656,195,'programacion.despacho@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(657,195,'ecommerce.lurin@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(658,196,'miguel.garcia@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(659,196,'frank.prado@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(660,196,'programacion.despacho@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(661,196,'ecommerce.lurin@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(662,197,'miguel.garcia@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(663,197,'frank.prado@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(664,197,'programacion.despacho@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(665,197,'ecommerce.lurin@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(666,198,'miguel.garcia@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(667,198,'frank.prado@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(668,198,'programacion.despacho@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(669,198,'ecommerce.lurin@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(670,199,'miguel.garcia@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(671,199,'frank.prado@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(672,199,'programacion.despacho@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(673,199,'ecommerce.lurin@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(674,200,'miguel.garcia@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(675,200,'frank.prado@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(676,200,'programacion.despacho@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(677,200,'ecommerce.lurin@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(678,201,'miguel.garcia@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(679,201,'frank.prado@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(680,201,'programacion.despacho@boostersolutions.com','',1,0)
insert into "@EX_CONTACT" (Code,U_EX_RUTA,Email,Password,Type,State) values(681,201,'ecommerce.lurin@boostersolutions.com','',1,0)
--select * from [dbo].[@EX_LOG] where U_EX_RUTA >= 160
--select count(*) from [dbo].[@EX_LOG] where U_EX_RUTA = 160
--delete from [dbo].[@EX_LOG] where U_EX_RUTA = 160
--delete from "@EX_CONTACT" where U_EX_RUTA >= 160
--select * from "@EX_CONTACT" where U_EX_RUTA = 160
--select * from SAP_HOST_DESPACHO
--truncate table SAP_HOST_DESPACHO

select * from [@EX_PLANIFICADO] where U_EX_PROCESO in ('SAP_UPDATE_DESPACHO')
select * from [@EX_PLANIFICADO] where U_EX_PROCESO in ('SAP_UPDATE_LIQUIDACION')
--ALTER TABLE "@EX_FILE"
--ALTER COLUMN Prefix VARCHAR(250);